INSERT INTO public.bill (ID_BILL, CUSTOMER_BILL, PRODUCT_BILL, TOTAL_PRICE)
VALUES (RANDOM_UUID(), 'Jhon', 'courses/Java', 500);
INSERT INTO public.bill (ID_BILL, CUSTOMER_BILL, PRODUCT_BILL, TOTAL_PRICE)
VALUES (RANDOM_UUID(), 'Michael', 'courses/Java', 500);
INSERT INTO public.bill (ID_BILL, CUSTOMER_BILL, PRODUCT_BILL, TOTAL_PRICE)
VALUES (RANDOM_UUID(), 'Peter', 'courses/Java', 500);
INSERT INTO public.bill (ID_BILL, CUSTOMER_BILL, PRODUCT_BILL, TOTAL_PRICE)
VALUES (RANDOM_UUID(), 'Sebastian', 'courses/Java', 500);
INSERT INTO public.bill (ID_BILL, CUSTOMER_BILL, PRODUCT_BILL, TOTAL_PRICE)
VALUES (RANDOM_UUID(), 'Aaron', 'courses/Java', 500);
INSERT INTO public.bill (ID_BILL, CUSTOMER_BILL, PRODUCT_BILL, TOTAL_PRICE)
VALUES (RANDOM_UUID(), '0d374cd6-4f92-481c-9441-05e79b22740b', 'courses/Java', 500);
INSERT INTO public.bill (ID_BILL, CUSTOMER_BILL, PRODUCT_BILL, TOTAL_PRICE)
VALUES (RANDOM_UUID(), '0d374cd6-4f92-481c-9441-05e79b22740b', '2', 100);